server:
  port: 8080

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    url: jdbc:mysql://localhost:3306/library_system?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #下划线到驼峰
    map-underscore-to-camel-case: true
